# Top 200 Cryptocurrencies by Market Cap
# This list includes the most popular and liquid cryptocurrencies for analysis

TOP_200_CRYPTOS = {
    # Top 10
    "Bitcoin (BTC)": "BTC",
    "Ethereum (ETH)": "ETH", 
    "Tether (USDT)": "USDT",
    "BNB (BNB)": "BNB",
    "Solana (SOL)": "SOL",
    "USDC (USDC)": "USDC",
    "XRP (XRP)": "XRP",
    "Lido Staked Ether (STETH)": "STETH",
    "Cardano (ADA)": "ADA",
    "Dogecoin (DOGE)": "DOGE",
    
    # 11-20
    "TRON (TRX)": "TRX",
    "Avalanche (AVAX)": "AVAX",
    "Wrapped Bitcoin (WBTC)": "WBTC",
    "Chainlink (LINK)": "LINK",
    "Polygon (MATIC)": "MATIC",
    "Polkadot (DOT)": "DOT",
    "Litecoin (LTC)": "LTC",
    "Internet Computer (ICP)": "ICP",
    "Uniswap (UNI)": "UNI",
    "Ethereum Classic (ETC)": "ETC",
    
    # 21-40
    "Stellar (XLM)": "XLM",
    "Monero (XMR)": "XMR",
    "Bitcoin Cash (BCH)": "BCH",
    "Cosmos (ATOM)": "ATOM",
    "Filecoin (FIL)": "FIL",
    "Hedera (HBAR)": "HBAR",
    "Cronos (CRO)": "CRO",
    "VeChain (VET)": "VET",
    "Algorand (ALGO)": "ALGO",
    "Quant (QNT)": "QNT",
    "Near Protocol (NEAR)": "NEAR",
    "Flow (FLOW)": "FLOW",
    "ApeCoin (APE)": "APE",
    "Sandbox (SAND)": "SAND",
    "Decentraland (MANA)": "MANA",
    "Theta Network (THETA)": "THETA",
    "Axie Infinity (AXS)": "AXS",
    "Elrond (EGLD)": "EGLD",
    "Tezos (XTZ)": "XTZ",
    "Aave (AAVE)": "AAVE",
    
    # 41-60
    "EOS (EOS)": "EOS",
    "Klaytn (KLAY)": "KLAY",
    "Bitcoin SV (BSV)": "BSV",
    "Maker (MKR)": "MKR",
    "Fantom (FTM)": "FTM",
    "Curve DAO Token (CRV)": "CRV",
    "PancakeSwap (CAKE)": "CAKE",
    "Chiliz (CHZ)": "CHZ",
    "Zcash (ZEC)": "ZEC",
    "Mina (MINA)": "MINA",
    "Dash (DASH)": "DASH",
    "IOTA (MIOTA)": "MIOTA",
    "NEO (NEO)": "NEO",
    "Compound (COMP)": "COMP",
    "Synthetix (SNX)": "SNX",
    "Enjin Coin (ENJ)": "ENJ",
    "1inch Network (1INCH)": "1INCH",
    "Sushi (SUSHI)": "SUSHI",
    "Yearn.finance (YFI)": "YFI",
    "Basic Attention Token (BAT)": "BAT",
    
    # 61-80
    "Zilliqa (ZIL)": "ZIL",
    "OMG Network (OMG)": "OMG",
    "0x (ZRX)": "ZRX",
    "Loopring (LRC)": "LRC",
    "Bancor (BNT)": "BNT",
    "Kyber Network (KNC)": "KNC",
    "Augur (REP)": "REP",
    "Gnosis (GNO)": "GNO",
    "Storj (STORJ)": "STORJ",
    "Numeraire (NMR)": "NMR",
    "district0x (DNT)": "DNT",
    "Civic (CVC)": "CVC",
    "Metal (MTL)": "MTL",
    "TenX (PAY)": "PAY",
    "AdEx (ADX)": "ADX",
    "Aragon (ANT)": "ANT",
    "Status (SNT)": "SNT",
    "Power Ledger (POWR)": "POWR",
    "Request Network (REQ)": "REQ",
    "Quantstamp (QSP)": "QSP",
    
    # 81-100
    "Golem (GLM)": "GLM",
    "Polymath (POLY)": "POLY",
    "Loom Network (LOOM)": "LOOM",
    "Decred (DCR)": "DCR",
    "Horizen (ZEN)": "ZEN",
    "Ravencoin (RVN)": "RVN",
    "Verge (XVG)": "XVG",
    "DigiByte (DGB)": "DGB",
    "Siacoin (SC)": "SC",
    "Steem (STEEM)": "STEEM",
    "Lisk (LSK)": "LSK",
    "Stratis (STRAX)": "STRAX",
    "Waves (WAVES)": "WAVES",
    "Nano (NANO)": "NANO",
    "Komodo (KMD)": "KMD",
    "Ark (ARK)": "ARK",
    "Electroneum (ETN)": "ETN",
    "PIVX (PIVX)": "PIVX",
    "Vertcoin (VTC)": "VTC",
    "MonaCoin (MONA)": "MONA",
    
    # 101-120
    "Shiba Inu (SHIB)": "SHIB",
    "Pepe (PEPE)": "PEPE",
    "Floki (FLOKI)": "FLOKI",
    "SafeMoon (SAFEMOON)": "SAFEMOON",
    "Baby Doge Coin (BABYDOGE)": "BABYDOGE",
    "Dogelon Mars (ELON)": "ELON",
    "Akita Inu (AKITA)": "AKITA",
    "Kishu Inu (KISHU)": "KISHU",
    "Hoge Finance (HOGE)": "HOGE",
    "Samoyedcoin (SAMO)": "SAMO",
    "Catgirl (CATGIRL)": "CATGIRL",
    "MonkeyBall (MBS)": "MBS",
    "CateCoin (CATE)": "CATE",
    "Pitbull (PIT)": "PIT",
    "SafeMars (SAFEMARS)": "SAFEMARS",
    "FEG Token (FEG)": "FEG",
    "Elongate (ELONGATE)": "ELONGATE",
    "MoonPirate (MOONPIRATE)": "MOONPIRATE",
    "SafeGalaxy (SAFEGALAXY)": "SAFEGALAXY",
    
    # 121-140
    "Render Token (RNDR)": "RNDR",
    "Immutable X (IMX)": "IMX",
    "Gala (GALA)": "GALA",
    "Smooth Love Potion (SLP)": "SLP",
    "My Neighbor Alice (ALICE)": "ALICE",
    "Star Atlas (ATLAS)": "ATLAS",
    "Illuvium (ILV)": "ILV",
    "Gods Unchained (GODS)": "GODS",
    "Ultra (UOS)": "UOS",
    "Chromia (CHR)": "CHR",
    "WAX (WAXP)": "WAXP",
    "Alien Worlds (TLM)": "TLM",
    "RadioCaca (RACA)": "RACA",
    "MOBOX (MBOX)": "MBOX",
    "BinaryX (BNX)": "BNX",
    "Yield Guild Games (YGG)": "YGG",
    "Merit Circle (MC)": "MC",
    "GameFi (GAFI)": "GAFI",
    "Vulcan Forged PYR (PYR)": "PYR",
    "SIDUS (SIDUS)": "SIDUS",
    
    # 141-160
    "Band Protocol (BAND)": "BAND",
    "API3 (API3)": "API3",
    "Tellor (TRB)": "TRB",
    "DIA (DIA)": "DIA",
    "Razor Network (RAZOR)": "RAZOR",
    "Umbrella Network (UMB)": "UMB",
    "SupraOracles (SUPRA)": "SUPRA",
    "Pyth Network (PYTH)": "PYTH",
    "Chronicle (XNL)": "XNL",
    "Flux (FLUX)": "FLUX",
    "RedStone (RED)": "RED",
    "WINkLink (WIN)": "WIN",
    "Nest Protocol (NEST)": "NEST",
    "DOS Network (DOS)": "DOS",
    "Orion Protocol (ORN)": "ORN",
    "Bridge Oracle (BRG)": "BRG",
    "Zap (ZAP)": "ZAP",
    "PARSIQ (PRQ)": "PRQ",
    "Witnet (WIT)": "WIT",
    
    # 161-180
    "Balancer (BAL)": "BAL",
    "UMA (UMA)": "UMA",
    "Badger DAO (BADGER)": "BADGER",
    "Harvest Finance (FARM)": "FARM",
    "Alpha Finance Lab (ALPHA)": "ALPHA",
    "Cream Finance (CREAM)": "CREAM",
    "bZx Protocol (BZRX)": "BZRX",
    "Ampleforth (AMPL)": "AMPL",
    "Reflexer Ungovernance Token (FLX)": "FLX",
    "Liquity (LQTY)": "LQTY",
    
    # 181-200
    "Arbitrum (ARB)": "ARB",
    "Optimism (OP)": "OP",
    "Immutable X (IMX)": "IMX",
    "Loopring (LRC)": "LRC",
    "zkSync (ZKS)": "ZKS",
    "StarkNet (STRK)": "STRK",
    "Metis (METIS)": "METIS",
    "Boba Network (BOBA)": "BOBA",
    "Hermez Network (HEZ)": "HEZ",
    "Celer Network (CELR)": "CELR",
    "Skale Network (SKL)": "SKL",
    "Cartesi (CTSI)": "CTSI",
    "Offchain Labs (OFFCHAIN)": "OFFCHAIN",
    "Matter Labs (MATTER)": "MATTER",
    "Polygon Hermez (HERMEZ)": "HERMEZ",
    "Aztec Protocol (AZTEC)": "AZTEC",
    "Fuel Network (FUEL)": "FUEL",
    "Scroll (SCROLL)": "SCROLL",
    "Taiko (TAIKO)": "TAIKO"
}

# Create lists ordered by market cap for better UX
def get_sorted_crypto_list():
    """Return a list of cryptocurrency names ordered by market cap (approximate)"""
    # Return in the order defined (which follows market cap ranking)
    return list(TOP_200_CRYPTOS.keys())

def get_alphabetically_sorted_crypto_list():
    """Return an alphabetically sorted list of cryptocurrency names"""
    return sorted(TOP_200_CRYPTOS.keys())

def get_symbol_from_name(crypto_name):
    """Get the symbol for a given cryptocurrency name"""
    return TOP_200_CRYPTOS.get(crypto_name, "BTC")

def get_symbol_map():
    """Return the complete symbol mapping dictionary"""
    return TOP_200_CRYPTOS.copy()
